"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.sample_compact import SampleCompact
globals()['SampleCompact'] = SampleCompact
from ICA_SDK.model.sequencing_run_analysis_sample_configuration_compact import SequencingRunAnalysisSampleConfigurationCompact


class TestSequencingRunAnalysisSampleConfigurationCompact(unittest.TestCase):
    """SequencingRunAnalysisSampleConfigurationCompact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSequencingRunAnalysisSampleConfigurationCompact(self):
        """Test SequencingRunAnalysisSampleConfigurationCompact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SequencingRunAnalysisSampleConfigurationCompact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
