"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.lane_by_read_sequencing_stats import LaneByReadSequencingStats


class TestLaneByReadSequencingStats(unittest.TestCase):
    """LaneByReadSequencingStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLaneByReadSequencingStats(self):
        """Test LaneByReadSequencingStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LaneByReadSequencingStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
