"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.lane_content_response import LaneContentResponse
globals()['LaneContentResponse'] = LaneContentResponse
from ICA_SDK.model.sequencing_run_contents_response import SequencingRunContentsResponse


class TestSequencingRunContentsResponse(unittest.TestCase):
    """SequencingRunContentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSequencingRunContentsResponse(self):
        """Test SequencingRunContentsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SequencingRunContentsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
