"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.analysis_version_definition_compact_item_list import AnalysisVersionDefinitionCompactItemList
globals()['AnalysisVersionDefinitionCompactItemList'] = AnalysisVersionDefinitionCompactItemList
from ICA_SDK.model.analysis_definition_compact import AnalysisDefinitionCompact


class TestAnalysisDefinitionCompact(unittest.TestCase):
    """AnalysisDefinitionCompact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalysisDefinitionCompact(self):
        """Test AnalysisDefinitionCompact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnalysisDefinitionCompact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
