"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.index_adapter_kit_settings_response import IndexAdapterKitSettingsResponse
from ICA_SDK.model.index_sequence import IndexSequence
from ICA_SDK.model.library_prep_kit_compact import LibraryPrepKitCompact
globals()['IndexAdapterKitSettingsResponse'] = IndexAdapterKitSettingsResponse
globals()['IndexSequence'] = IndexSequence
globals()['LibraryPrepKitCompact'] = LibraryPrepKitCompact
from ICA_SDK.model.index_adapter_kit import IndexAdapterKit


class TestIndexAdapterKit(unittest.TestCase):
    """IndexAdapterKit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndexAdapterKit(self):
        """Test IndexAdapterKit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndexAdapterKit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
