"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.genome import Genome


class TestGenome(unittest.TestCase):
    """Genome unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenome(self):
        """Test Genome"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Genome()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
