"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.sequencing_run_configuration import SequencingRunConfiguration


class TestSequencingRunConfiguration(unittest.TestCase):
    """SequencingRunConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSequencingRunConfiguration(self):
        """Test SequencingRunConfiguration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SequencingRunConfiguration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
