"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.instrument import Instrument
from ICA_SDK.model.sequencing_run_analysis_summary import SequencingRunAnalysisSummary
from ICA_SDK.model.sequencing_run_configuration import SequencingRunConfiguration
from ICA_SDK.model.sequencing_run_genome_info import SequencingRunGenomeInfo
from ICA_SDK.model.sequencing_run_prep_kit_info import SequencingRunPrepKitInfo
globals()['Instrument'] = Instrument
globals()['SequencingRunAnalysisSummary'] = SequencingRunAnalysisSummary
globals()['SequencingRunConfiguration'] = SequencingRunConfiguration
globals()['SequencingRunGenomeInfo'] = SequencingRunGenomeInfo
globals()['SequencingRunPrepKitInfo'] = SequencingRunPrepKitInfo
from ICA_SDK.model.sequencing_run_compact import SequencingRunCompact


class TestSequencingRunCompact(unittest.TestCase):
    """SequencingRunCompact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSequencingRunCompact(self):
        """Test SequencingRunCompact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SequencingRunCompact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
