"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.execution import Execution
globals()['Execution'] = Execution
from ICA_SDK.model.create_task_run_request import CreateTaskRunRequest


class TestCreateTaskRunRequest(unittest.TestCase):
    """CreateTaskRunRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTaskRunRequest(self):
        """Test CreateTaskRunRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTaskRunRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
