"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.delivery_target import DeliveryTarget
globals()['DeliveryTarget'] = DeliveryTarget
from ICA_SDK.model.create_subscription_request import CreateSubscriptionRequest


class TestCreateSubscriptionRequest(unittest.TestCase):
    """CreateSubscriptionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateSubscriptionRequest(self):
        """Test CreateSubscriptionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateSubscriptionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
