"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.object_store_settings import ObjectStoreSettings
globals()['ObjectStoreSettings'] = ObjectStoreSettings
from ICA_SDK.model.create_volume_configuration_request import CreateVolumeConfigurationRequest


class TestCreateVolumeConfigurationRequest(unittest.TestCase):
    """CreateVolumeConfigurationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateVolumeConfigurationRequest(self):
        """Test CreateVolumeConfigurationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateVolumeConfigurationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
