"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import ICA_SDK
from ICA_SDK.api.workgroups_api import WorkgroupsApi  # noqa: E501


class TestWorkgroupsApi(unittest.TestCase):
    """WorkgroupsApi unit test stubs"""

    def setUp(self):
        self.api = WorkgroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_workgroups(self):
        """Test case for list_workgroups

        Get a list of available workgroups. Requires session token (psToken) authorization Bearer token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
