"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.flow_cell_type import FlowCellType
from ICA_SDK.model.multi_analysis_configuration import MultiAnalysisConfiguration
globals()['FlowCellType'] = FlowCellType
globals()['MultiAnalysisConfiguration'] = MultiAnalysisConfiguration
from ICA_SDK.model.instrument_type_info import InstrumentTypeInfo


class TestInstrumentTypeInfo(unittest.TestCase):
    """InstrumentTypeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstrumentTypeInfo(self):
        """Test InstrumentTypeInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstrumentTypeInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
