"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.supported_instrument_platform_and_types import SupportedInstrumentPlatformAndTypes


class TestSupportedInstrumentPlatformAndTypes(unittest.TestCase):
    """SupportedInstrumentPlatformAndTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupportedInstrumentPlatformAndTypes(self):
        """Test SupportedInstrumentPlatformAndTypes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SupportedInstrumentPlatformAndTypes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
