"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.execution import Execution
globals()['Execution'] = Execution
from ICA_SDK.model.task_version import TaskVersion


class TestTaskVersion(unittest.TestCase):
    """TaskVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskVersion(self):
        """Test TaskVersion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskVersion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
