"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.bulk_update_failed_item import BulkUpdateFailedItem
globals()['BulkUpdateFailedItem'] = BulkUpdateFailedItem
from ICA_SDK.model.bulk_file_update_response import BulkFileUpdateResponse


class TestBulkFileUpdateResponse(unittest.TestCase):
    """BulkFileUpdateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBulkFileUpdateResponse(self):
        """Test BulkFileUpdateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BulkFileUpdateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
