"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.genome_compact import GenomeCompact
globals()['GenomeCompact'] = GenomeCompact
from ICA_SDK.model.genome_compact_genome_sort_fields_paged_items import GenomeCompactGenomeSortFieldsPagedItems


class TestGenomeCompactGenomeSortFieldsPagedItems(unittest.TestCase):
    """GenomeCompactGenomeSortFieldsPagedItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenomeCompactGenomeSortFieldsPagedItems(self):
        """Test GenomeCompactGenomeSortFieldsPagedItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GenomeCompactGenomeSortFieldsPagedItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
