"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.session_status import SessionStatus


class TestSessionStatus(unittest.TestCase):
    """SessionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionStatus(self):
        """Test SessionStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SessionStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
