"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.default_kit import DefaultKit
globals()['DefaultKit'] = DefaultKit
from ICA_SDK.model.import_planned_run_request import ImportPlannedRunRequest


class TestImportPlannedRunRequest(unittest.TestCase):
    """ImportPlannedRunRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImportPlannedRunRequest(self):
        """Test ImportPlannedRunRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImportPlannedRunRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
