"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.lane_content import LaneContent
globals()['LaneContent'] = LaneContent
from ICA_SDK.model.update_sequencing_run_contents_request import UpdateSequencingRunContentsRequest


class TestUpdateSequencingRunContentsRequest(unittest.TestCase):
    """UpdateSequencingRunContentsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSequencingRunContentsRequest(self):
        """Test UpdateSequencingRunContentsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateSequencingRunContentsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
