"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.container_state_waiting import ContainerStateWaiting


class TestContainerStateWaiting(unittest.TestCase):
    """ContainerStateWaiting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainerStateWaiting(self):
        """Test ContainerStateWaiting"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContainerStateWaiting()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
