"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.workflow_language import WorkflowLanguage
globals()['WorkflowLanguage'] = WorkflowLanguage
from ICA_SDK.model.create_workflow_version_request import CreateWorkflowVersionRequest


class TestCreateWorkflowVersionRequest(unittest.TestCase):
    """CreateWorkflowVersionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateWorkflowVersionRequest(self):
        """Test CreateWorkflowVersionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateWorkflowVersionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
