"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.system_files import SystemFiles


class TestSystemFiles(unittest.TestCase):
    """SystemFiles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemFiles(self):
        """Test SystemFiles"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SystemFiles()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
