"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.volume_life_cycle_settings import VolumeLifeCycleSettings
globals()['VolumeLifeCycleSettings'] = VolumeLifeCycleSettings
from ICA_SDK.model.create_volume_request import CreateVolumeRequest


class TestCreateVolumeRequest(unittest.TestCase):
    """CreateVolumeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateVolumeRequest(self):
        """Test CreateVolumeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateVolumeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
