"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.sequencing_run_compact import SequencingRunCompact
globals()['SequencingRunCompact'] = SequencingRunCompact
from ICA_SDK.model.sequencing_analysis_run_compact import SequencingAnalysisRunCompact


class TestSequencingAnalysisRunCompact(unittest.TestCase):
    """SequencingAnalysisRunCompact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSequencingAnalysisRunCompact(self):
        """Test SequencingAnalysisRunCompact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SequencingAnalysisRunCompact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
