"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.library_prep_kit_settings import LibraryPrepKitSettings
globals()['LibraryPrepKitSettings'] = LibraryPrepKitSettings
from ICA_SDK.model.update_library_prep_kit_request import UpdateLibraryPrepKitRequest


class TestUpdateLibraryPrepKitRequest(unittest.TestCase):
    """UpdateLibraryPrepKitRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateLibraryPrepKitRequest(self):
        """Test UpdateLibraryPrepKitRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateLibraryPrepKitRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
