"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.folder_archive_storage_tier import FolderArchiveStorageTier


class TestFolderArchiveStorageTier(unittest.TestCase):
    """FolderArchiveStorageTier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFolderArchiveStorageTier(self):
        """Test FolderArchiveStorageTier"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FolderArchiveStorageTier()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
