"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.create_sequencing_run_configuration_request import CreateSequencingRunConfigurationRequest


class TestCreateSequencingRunConfigurationRequest(unittest.TestCase):
    """CreateSequencingRunConfigurationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateSequencingRunConfigurationRequest(self):
        """Test CreateSequencingRunConfigurationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateSequencingRunConfigurationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
