"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.library_prep_kit_and_index_adapter_kit_name import LibraryPrepKitAndIndexAdapterKitName
globals()['LibraryPrepKitAndIndexAdapterKitName'] = LibraryPrepKitAndIndexAdapterKitName
from ICA_SDK.model.lane_prep_kit_info import LanePrepKitInfo


class TestLanePrepKitInfo(unittest.TestCase):
    """LanePrepKitInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLanePrepKitInfo(self):
        """Test LanePrepKitInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LanePrepKitInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
