"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.input_stream_settings import InputStreamSettings
from ICA_SDK.model.resources import Resources
globals()['InputStreamSettings'] = InputStreamSettings
globals()['Resources'] = Resources
from ICA_SDK.model.environment import Environment


class TestEnvironment(unittest.TestCase):
    """Environment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnvironment(self):
        """Test Environment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Environment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
