"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.create_sequencing_run_analysis_configuration_request import CreateSequencingRunAnalysisConfigurationRequest
from ICA_SDK.model.create_sequencing_run_configuration_request import CreateSequencingRunConfigurationRequest
from ICA_SDK.model.update_sequencing_run_contents_request import UpdateSequencingRunContentsRequest
globals()['CreateSequencingRunAnalysisConfigurationRequest'] = CreateSequencingRunAnalysisConfigurationRequest
globals()['CreateSequencingRunConfigurationRequest'] = CreateSequencingRunConfigurationRequest
globals()['UpdateSequencingRunContentsRequest'] = UpdateSequencingRunContentsRequest
from ICA_SDK.model.create_planned_run_request import CreatePlannedRunRequest


class TestCreatePlannedRunRequest(unittest.TestCase):
    """CreatePlannedRunRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatePlannedRunRequest(self):
        """Test CreatePlannedRunRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatePlannedRunRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
