"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.auxiliary_file_reference_compact import AuxiliaryFileReferenceCompact
from ICA_SDK.model.file_reference_compact import FileReferenceCompact
globals()['AuxiliaryFileReferenceCompact'] = AuxiliaryFileReferenceCompact
globals()['FileReferenceCompact'] = FileReferenceCompact
from ICA_SDK.model.sample_sheet import SampleSheet


class TestSampleSheet(unittest.TestCase):
    """SampleSheet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSampleSheet(self):
        """Test SampleSheet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SampleSheet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
