"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.product_usage import ProductUsage
from ICA_SDK.model.user import User
globals()['ProductUsage'] = ProductUsage
globals()['User'] = User
from ICA_SDK.model.user_aggregated_usage import UserAggregatedUsage


class TestUserAggregatedUsage(unittest.TestCase):
    """UserAggregatedUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserAggregatedUsage(self):
        """Test UserAggregatedUsage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserAggregatedUsage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
