"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.folder_copy_request import FolderCopyRequest


class TestFolderCopyRequest(unittest.TestCase):
    """FolderCopyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFolderCopyRequest(self):
        """Test FolderCopyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FolderCopyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
