"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.create_index_adapter_kit_by_definition_request import CreateIndexAdapterKitByDefinitionRequest


class TestCreateIndexAdapterKitByDefinitionRequest(unittest.TestCase):
    """CreateIndexAdapterKitByDefinitionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateIndexAdapterKitByDefinitionRequest(self):
        """Test CreateIndexAdapterKitByDefinitionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateIndexAdapterKitByDefinitionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
