"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.library_prep_kit_and_index_adapter_kit_name import LibraryPrepKitAndIndexAdapterKitName


class TestLibraryPrepKitAndIndexAdapterKitName(unittest.TestCase):
    """LibraryPrepKitAndIndexAdapterKitName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLibraryPrepKitAndIndexAdapterKitName(self):
        """Test LibraryPrepKitAndIndexAdapterKitName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LibraryPrepKitAndIndexAdapterKitName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
