"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.folder_update_request import FolderUpdateRequest


class TestFolderUpdateRequest(unittest.TestCase):
    """FolderUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFolderUpdateRequest(self):
        """Test FolderUpdateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FolderUpdateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
