"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.parsed_sequencing_run import ParsedSequencingRun
from ICA_SDK.model.sample_sheet_parsing_warning import SampleSheetParsingWarning
globals()['ParsedSequencingRun'] = ParsedSequencingRun
globals()['SampleSheetParsingWarning'] = SampleSheetParsingWarning
from ICA_SDK.model.parse_sample_sheet_response import ParseSampleSheetResponse


class TestParseSampleSheetResponse(unittest.TestCase):
    """ParseSampleSheetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParseSampleSheetResponse(self):
        """Test ParseSampleSheetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParseSampleSheetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
