"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.error_response import ErrorResponse
globals()['ErrorResponse'] = ErrorResponse
from ICA_SDK.model.bulk_update_failed_item import BulkUpdateFailedItem


class TestBulkUpdateFailedItem(unittest.TestCase):
    """BulkUpdateFailedItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBulkUpdateFailedItem(self):
        """Test BulkUpdateFailedItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BulkUpdateFailedItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
