"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.instrument_platform_info import InstrumentPlatformInfo
from ICA_SDK.model.instrument_type_info import InstrumentTypeInfo
globals()['InstrumentPlatformInfo'] = InstrumentPlatformInfo
globals()['InstrumentTypeInfo'] = InstrumentTypeInfo
from ICA_SDK.model.supported_instrument_types import SupportedInstrumentTypes


class TestSupportedInstrumentTypes(unittest.TestCase):
    """SupportedInstrumentTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupportedInstrumentTypes(self):
        """Test SupportedInstrumentTypes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SupportedInstrumentTypes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
