"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.period_usage_summary import PeriodUsageSummary
globals()['PeriodUsageSummary'] = PeriodUsageSummary
from ICA_SDK.model.usage_response import UsageResponse


class TestUsageResponse(unittest.TestCase):
    """UsageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsageResponse(self):
        """Test UsageResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UsageResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
