"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.index_adapter_kit_compact import IndexAdapterKitCompact
from ICA_SDK.model.library_prep_kit_compact import LibraryPrepKitCompact
from ICA_SDK.model.sample_compact import SampleCompact
globals()['IndexAdapterKitCompact'] = IndexAdapterKitCompact
globals()['LibraryPrepKitCompact'] = LibraryPrepKitCompact
globals()['SampleCompact'] = SampleCompact
from ICA_SDK.model.library import Library


class TestLibrary(unittest.TestCase):
    """Library unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLibrary(self):
        """Test Library"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Library()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
