"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.credentials import Credentials
globals()['Credentials'] = Credentials
from ICA_SDK.model.image import Image


class TestImage(unittest.TestCase):
    """Image unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImage(self):
        """Test Image"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Image()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
