"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.sample_setting_entry import SampleSettingEntry
globals()['SampleSettingEntry'] = SampleSettingEntry
from ICA_SDK.model.update_sequencing_run_analysis_configuration_request import UpdateSequencingRunAnalysisConfigurationRequest


class TestUpdateSequencingRunAnalysisConfigurationRequest(unittest.TestCase):
    """UpdateSequencingRunAnalysisConfigurationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSequencingRunAnalysisConfigurationRequest(self):
        """Test UpdateSequencingRunAnalysisConfigurationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateSequencingRunAnalysisConfigurationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
