"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.update_analysis_definition_request import UpdateAnalysisDefinitionRequest


class TestUpdateAnalysisDefinitionRequest(unittest.TestCase):
    """UpdateAnalysisDefinitionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateAnalysisDefinitionRequest(self):
        """Test UpdateAnalysisDefinitionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateAnalysisDefinitionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
