"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.bulk_folder_update_item import BulkFolderUpdateItem


class TestBulkFolderUpdateItem(unittest.TestCase):
    """BulkFolderUpdateItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBulkFolderUpdateItem(self):
        """Test BulkFolderUpdateItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BulkFolderUpdateItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
