"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.sequencing_run_prep_kit_info import SequencingRunPrepKitInfo
globals()['SequencingRunPrepKitInfo'] = SequencingRunPrepKitInfo
from ICA_SDK.model.update_sequencing_run_request import UpdateSequencingRunRequest


class TestUpdateSequencingRunRequest(unittest.TestCase):
    """UpdateSequencingRunRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSequencingRunRequest(self):
        """Test UpdateSequencingRunRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateSequencingRunRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
