"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.update_file_request import UpdateFileRequest


class TestUpdateFileRequest(unittest.TestCase):
    """UpdateFileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateFileRequest(self):
        """Test UpdateFileRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateFileRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
