"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.project import Project
globals()['Project'] = Project
from ICA_SDK.model.project_paged_items import ProjectPagedItems


class TestProjectPagedItems(unittest.TestCase):
    """ProjectPagedItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectPagedItems(self):
        """Test ProjectPagedItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectPagedItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
