"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.container_status import ContainerStatus
globals()['ContainerStatus'] = ContainerStatus
from ICA_SDK.model.heartbeat_task_run_request import HeartbeatTaskRunRequest


class TestHeartbeatTaskRunRequest(unittest.TestCase):
    """HeartbeatTaskRunRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHeartbeatTaskRunRequest(self):
        """Test HeartbeatTaskRunRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HeartbeatTaskRunRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
