"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.close_run_upload_session_request import CloseRunUploadSessionRequest


class TestCloseRunUploadSessionRequest(unittest.TestCase):
    """CloseRunUploadSessionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloseRunUploadSessionRequest(self):
        """Test CloseRunUploadSessionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CloseRunUploadSessionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
