"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.archive_statuses import ArchiveStatuses
from ICA_SDK.model.file_life_cycle_settings import FileLifeCycleSettings
from ICA_SDK.model.file_status import FileStatus
from ICA_SDK.model.storage_tier import StorageTier
globals()['ArchiveStatuses'] = ArchiveStatuses
globals()['FileLifeCycleSettings'] = FileLifeCycleSettings
globals()['FileStatus'] = FileStatus
globals()['StorageTier'] = StorageTier
from ICA_SDK.model.file_response import FileResponse


class TestFileResponse(unittest.TestCase):
    """FileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileResponse(self):
        """Test FileResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
