"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.workflow_run_history_event import WorkflowRunHistoryEvent
globals()['WorkflowRunHistoryEvent'] = WorkflowRunHistoryEvent
from ICA_SDK.model.workflow_run_history_event_list import WorkflowRunHistoryEventList


class TestWorkflowRunHistoryEventList(unittest.TestCase):
    """WorkflowRunHistoryEventList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflowRunHistoryEventList(self):
        """Test WorkflowRunHistoryEventList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkflowRunHistoryEventList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
