"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.analysis_definition_compact import AnalysisDefinitionCompact
from ICA_SDK.model.analysis_version_definition_settings import AnalysisVersionDefinitionSettings
from ICA_SDK.model.instrument_platform_and_types_response import InstrumentPlatformAndTypesResponse
globals()['AnalysisDefinitionCompact'] = AnalysisDefinitionCompact
globals()['AnalysisVersionDefinitionSettings'] = AnalysisVersionDefinitionSettings
globals()['InstrumentPlatformAndTypesResponse'] = InstrumentPlatformAndTypesResponse
from ICA_SDK.model.analysis_version_definition_compact import AnalysisVersionDefinitionCompact


class TestAnalysisVersionDefinitionCompact(unittest.TestCase):
    """AnalysisVersionDefinitionCompact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalysisVersionDefinitionCompact(self):
        """Test AnalysisVersionDefinitionCompact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnalysisVersionDefinitionCompact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
