"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.folder_response import FolderResponse
globals()['FolderResponse'] = FolderResponse
from ICA_SDK.model.folder_list_response import FolderListResponse


class TestFolderListResponse(unittest.TestCase):
    """FolderListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFolderListResponse(self):
        """Test FolderListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FolderListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
