"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.start_planned_run_request import StartPlannedRunRequest


class TestStartPlannedRunRequest(unittest.TestCase):
    """StartPlannedRunRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStartPlannedRunRequest(self):
        """Test StartPlannedRunRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StartPlannedRunRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
