"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.library_prep_kit_compact import LibraryPrepKitCompact
globals()['LibraryPrepKitCompact'] = LibraryPrepKitCompact
from ICA_SDK.model.library_prep_kit_compact_library_prep_kit_sort_fields_paged_items import LibraryPrepKitCompactLibraryPrepKitSortFieldsPagedItems


class TestLibraryPrepKitCompactLibraryPrepKitSortFieldsPagedItems(unittest.TestCase):
    """LibraryPrepKitCompactLibraryPrepKitSortFieldsPagedItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLibraryPrepKitCompactLibraryPrepKitSortFieldsPagedItems(self):
        """Test LibraryPrepKitCompactLibraryPrepKitSortFieldsPagedItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LibraryPrepKitCompactLibraryPrepKitSortFieldsPagedItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
