"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.library_pool_compact import LibraryPoolCompact
globals()['LibraryPoolCompact'] = LibraryPoolCompact
from ICA_SDK.model.library_pool_compact_library_pool_sort_fields_paged_items import LibraryPoolCompactLibraryPoolSortFieldsPagedItems


class TestLibraryPoolCompactLibraryPoolSortFieldsPagedItems(unittest.TestCase):
    """LibraryPoolCompactLibraryPoolSortFieldsPagedItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLibraryPoolCompactLibraryPoolSortFieldsPagedItems(self):
        """Test LibraryPoolCompactLibraryPoolSortFieldsPagedItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LibraryPoolCompactLibraryPoolSortFieldsPagedItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
