"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.aws_s3_temporary_upload_credentials import AwsS3TemporaryUploadCredentials
from ICA_SDK.model.direct_upload_credentials import DirectUploadCredentials
globals()['AwsS3TemporaryUploadCredentials'] = AwsS3TemporaryUploadCredentials
globals()['DirectUploadCredentials'] = DirectUploadCredentials
from ICA_SDK.model.object_store_access import ObjectStoreAccess


class TestObjectStoreAccess(unittest.TestCase):
    """ObjectStoreAccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectStoreAccess(self):
        """Test ObjectStoreAccess"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ObjectStoreAccess()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
