"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.library_prep_kit_settings_response import LibraryPrepKitSettingsResponse
globals()['LibraryPrepKitSettingsResponse'] = LibraryPrepKitSettingsResponse
from ICA_SDK.model.library_prep_kit_compact import LibraryPrepKitCompact


class TestLibraryPrepKitCompact(unittest.TestCase):
    """LibraryPrepKitCompact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLibraryPrepKitCompact(self):
        """Test LibraryPrepKitCompact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LibraryPrepKitCompact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
