"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.task_version_summary import TaskVersionSummary
globals()['TaskVersionSummary'] = TaskVersionSummary
from ICA_SDK.model.task_version_summary_paged_items import TaskVersionSummaryPagedItems


class TestTaskVersionSummaryPagedItems(unittest.TestCase):
    """TaskVersionSummaryPagedItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskVersionSummaryPagedItems(self):
        """Test TaskVersionSummaryPagedItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskVersionSummaryPagedItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
