"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.index_adapter_kit_compact import IndexAdapterKitCompact
globals()['IndexAdapterKitCompact'] = IndexAdapterKitCompact
from ICA_SDK.model.index_adapter_kit_compact_index_adapter_kit_sort_field_paged_items import IndexAdapterKitCompactIndexAdapterKitSortFieldPagedItems


class TestIndexAdapterKitCompactIndexAdapterKitSortFieldPagedItems(unittest.TestCase):
    """IndexAdapterKitCompactIndexAdapterKitSortFieldPagedItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndexAdapterKitCompactIndexAdapterKitSortFieldPagedItems(self):
        """Test IndexAdapterKitCompactIndexAdapterKitSortFieldPagedItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndexAdapterKitCompactIndexAdapterKitSortFieldPagedItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
