"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.product_usage import ProductUsage
from ICA_SDK.model.user_aggregated_usage import UserAggregatedUsage
globals()['ProductUsage'] = ProductUsage
globals()['UserAggregatedUsage'] = UserAggregatedUsage
from ICA_SDK.model.period_usage_summary import PeriodUsageSummary


class TestPeriodUsageSummary(unittest.TestCase):
    """PeriodUsageSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPeriodUsageSummary(self):
        """Test PeriodUsageSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PeriodUsageSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
