"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.health_check_statuses import HealthCheckStatuses


class TestHealthCheckStatuses(unittest.TestCase):
    """HealthCheckStatuses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHealthCheckStatuses(self):
        """Test HealthCheckStatuses"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HealthCheckStatuses()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
