"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.sequencing_run_genome import SequencingRunGenome
globals()['SequencingRunGenome'] = SequencingRunGenome
from ICA_SDK.model.sequencing_run_genome_info import SequencingRunGenomeInfo


class TestSequencingRunGenomeInfo(unittest.TestCase):
    """SequencingRunGenomeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSequencingRunGenomeInfo(self):
        """Test SequencingRunGenomeInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SequencingRunGenomeInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
