"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.analysis_dataset_compact import AnalysisDatasetCompact
globals()['AnalysisDatasetCompact'] = AnalysisDatasetCompact
from ICA_SDK.model.sample import Sample


class TestSample(unittest.TestCase):
    """Sample unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSample(self):
        """Test Sample"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Sample()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
