"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.update_sequencing_run_status_request import UpdateSequencingRunStatusRequest


class TestUpdateSequencingRunStatusRequest(unittest.TestCase):
    """UpdateSequencingRunStatusRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSequencingRunStatusRequest(self):
        """Test UpdateSequencingRunStatusRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateSequencingRunStatusRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
