"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.credentials import Credentials


class TestCredentials(unittest.TestCase):
    """Credentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredentials(self):
        """Test Credentials"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Credentials()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
