"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.analysis_definition_compact import AnalysisDefinitionCompact
globals()['AnalysisDefinitionCompact'] = AnalysisDefinitionCompact
from ICA_SDK.model.analysis_definition_compact_analysis_definition_sort_fields_paged_items import AnalysisDefinitionCompactAnalysisDefinitionSortFieldsPagedItems


class TestAnalysisDefinitionCompactAnalysisDefinitionSortFieldsPagedItems(unittest.TestCase):
    """AnalysisDefinitionCompactAnalysisDefinitionSortFieldsPagedItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalysisDefinitionCompactAnalysisDefinitionSortFieldsPagedItems(self):
        """Test AnalysisDefinitionCompactAnalysisDefinitionSortFieldsPagedItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnalysisDefinitionCompactAnalysisDefinitionSortFieldsPagedItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
