"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.create_task_version_request import CreateTaskVersionRequest
globals()['CreateTaskVersionRequest'] = CreateTaskVersionRequest
from ICA_SDK.model.create_task_request import CreateTaskRequest


class TestCreateTaskRequest(unittest.TestCase):
    """CreateTaskRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTaskRequest(self):
        """Test CreateTaskRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTaskRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
