"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.task_summary import TaskSummary
globals()['TaskSummary'] = TaskSummary
from ICA_SDK.model.task_summary_paged_items import TaskSummaryPagedItems


class TestTaskSummaryPagedItems(unittest.TestCase):
    """TaskSummaryPagedItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskSummaryPagedItems(self):
        """Test TaskSummaryPagedItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskSummaryPagedItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
