"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ICA_SDK
from ICA_SDK.model.file_archive_storage_tier import FileArchiveStorageTier
globals()['FileArchiveStorageTier'] = FileArchiveStorageTier
from ICA_SDK.model.file_archive_request import FileArchiveRequest


class TestFileArchiveRequest(unittest.TestCase):
    """FileArchiveRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileArchiveRequest(self):
        """Test FileArchiveRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileArchiveRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
