# coding: utf-8

"""
    Workflow Execution Service

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.workflow_run_history_event_list import WorkflowRunHistoryEventList  # noqa: E501
from swagger_client.rest import ApiException


class TestWorkflowRunHistoryEventList(unittest.TestCase):
    """WorkflowRunHistoryEventList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflowRunHistoryEventList(self):
        """Test WorkflowRunHistoryEventList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.workflow_run_history_event_list.WorkflowRunHistoryEventList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
