# coding: utf-8

"""
    Workflow Execution Service

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_workflow_version_request import CreateWorkflowVersionRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateWorkflowVersionRequest(unittest.TestCase):
    """CreateWorkflowVersionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateWorkflowVersionRequest(self):
        """Test CreateWorkflowVersionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_workflow_version_request.CreateWorkflowVersionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
