# coding: utf-8

"""
    Workflow Execution Service

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_workflow_request import UpdateWorkflowRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateWorkflowRequest(unittest.TestCase):
    """UpdateWorkflowRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateWorkflowRequest(self):
        """Test UpdateWorkflowRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_workflow_request.UpdateWorkflowRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
