"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from ICA_SDK.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class CreateSequencingRunConfigurationRequest(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('read_type',): {
            'SINGLE': "Single",
            'PAIRED': "Paired",
        },
        ('regulatory_mode',): {
            'RUO': "RUO",
            'IVD': "IVD",
            'IUO': "IUO",
        },
    }

    validations = {
        ('run_name',): {
            'max_length': 255,
            'min_length': 0,
        },
        ('num_cycles_read1',): {
            'inclusive_maximum': 2147483647,
            'inclusive_minimum': 0,
        },
        ('num_cycles_read2',): {
            'inclusive_maximum': 2147483647,
            'inclusive_minimum': 0,
        },
        ('num_cycles_index1',): {
            'inclusive_maximum': 2147483647,
            'inclusive_minimum': 0,
        },
        ('num_cycles_index2',): {
            'inclusive_maximum': 2147483647,
            'inclusive_minimum': 0,
        },
        ('description',): {
            'max_length': 8192,
            'min_length': 0,
        },
        ('input_container_identifier',): {
            'max_length': 255,
            'min_length': 0,
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'run_name': (str,),  # noqa: E501
            'num_cycles_read1': (int,),  # noqa: E501
            'num_cycles_read2': (int,),  # noqa: E501
            'read_type': (str,),  # noqa: E501
            'num_cycles_index1': (int,),  # noqa: E501
            'num_cycles_index2': (int,),  # noqa: E501
            'instrument_type': (str,),  # noqa: E501
            'instrument_platform': (str,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'regulatory_mode': (str,),  # noqa: E501
            'use_custom_primer_for_read1': (bool,),  # noqa: E501
            'use_custom_primer_for_read2': (bool,),  # noqa: E501
            'use_custom_primer_for_index1': (bool,),  # noqa: E501
            'use_custom_primer_for_index2': (bool,),  # noqa: E501
            'input_container_identifier': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'run_name': 'runName',  # noqa: E501
        'num_cycles_read1': 'numCyclesRead1',  # noqa: E501
        'num_cycles_read2': 'numCyclesRead2',  # noqa: E501
        'read_type': 'readType',  # noqa: E501
        'num_cycles_index1': 'numCyclesIndex1',  # noqa: E501
        'num_cycles_index2': 'numCyclesIndex2',  # noqa: E501
        'instrument_type': 'instrumentType',  # noqa: E501
        'instrument_platform': 'instrumentPlatform',  # noqa: E501
        'description': 'description',  # noqa: E501
        'regulatory_mode': 'regulatoryMode',  # noqa: E501
        'use_custom_primer_for_read1': 'useCustomPrimerForRead1',  # noqa: E501
        'use_custom_primer_for_read2': 'useCustomPrimerForRead2',  # noqa: E501
        'use_custom_primer_for_index1': 'useCustomPrimerForIndex1',  # noqa: E501
        'use_custom_primer_for_index2': 'useCustomPrimerForIndex2',  # noqa: E501
        'input_container_identifier': 'inputContainerIdentifier',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, run_name, num_cycles_read1, num_cycles_read2, read_type, num_cycles_index1, num_cycles_index2, *args, **kwargs):  # noqa: E501
        """CreateSequencingRunConfigurationRequest - a model defined in OpenAPI

        Args:
            run_name (str): Name of the run  Must not be null, empty, or consist only of white-space characters
            num_cycles_read1 (int): Number of cycles in read 1   Must not be a negative value
            num_cycles_read2 (int): Number of cycles in read 2  Must not be a negative value
            read_type (str): Read type of the run
            num_cycles_index1 (int): Number of cycles in index 1  Must not be a negative value
            num_cycles_index2 (int): Number of cycles in index 2  Must not be a negative value

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            instrument_type (str): Type of instrument for which the run is planned  Recognized values include:  iSeq100, MiniSeq,  MiSeq, MiSeqDx,  NextSeq, NextSeqDx,  HiSeq1000, HiSeq1500, HiSeq2000, HiSeq2500, HiSeq3000, HiSeq4000, HiSeqX  NovaSeq5000, NovaSeq6000.. [optional]  # noqa: E501
            instrument_platform (str): Platform of instrument for which the run is planned  Recognized values include:  NextSeq, HiSeq, MiSeq, Eco, iScan, HiSeqX, NeoPrep, MiniSeq, NovaSeq, iSeq, TruSightNIPT, NextSeq1k2k  No value entered is treated as the instrument platform of input InstrumentType. [optional]  # noqa: E501
            description (str): Description of the run. [optional]  # noqa: E501
            regulatory_mode (str): Regulatory mode of the run, default is RUO. [optional]  # noqa: E501
            use_custom_primer_for_read1 (bool): Value indicating whether read 1 uses custom primer. [optional]  # noqa: E501
            use_custom_primer_for_read2 (bool): Value indicating whether read 2 uses custom primer. [optional]  # noqa: E501
            use_custom_primer_for_index1 (bool): Value indicating whether index 1 uses custom primer.. [optional]  # noqa: E501
            use_custom_primer_for_index2 (bool): A value indicating whether index 2 uses custom primer. [optional]  # noqa: E501
            input_container_identifier (str): Input container identifier for planned run. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.run_name = run_name
        self.num_cycles_read1 = num_cycles_read1
        self.num_cycles_read2 = num_cycles_read2
        self.read_type = read_type
        self.num_cycles_index1 = num_cycles_index1
        self.num_cycles_index2 = num_cycles_index2
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
