"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from ICA_SDK.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from ICA_SDK.model.library_compact import LibraryCompact
    globals()['LibraryCompact'] = LibraryCompact


class LaneLibraryResponse(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'sample_name': (str,),  # noqa: E501
            'sample_urn': (str,),  # noqa: E501
            'data_aggregation_group': (str,),  # noqa: E501
            'project_name': (str,),  # noqa: E501
            'library_name': (str,),  # noqa: E501
            'library_urn': (str,),  # noqa: E501
            'adapter_sequence_read1': (str,),  # noqa: E501
            'adapter_sequence_read2': (str,),  # noqa: E501
            'index_container_position': (str,),  # noqa: E501
            'index1_sequence': (str,),  # noqa: E501
            'index2_sequence': (str,),  # noqa: E501
            'index1_name': (str,),  # noqa: E501
            'index2_name': (str,),  # noqa: E501
            'library_prep_kit_name': (str,),  # noqa: E501
            'library_prep_kit_urn': (str,),  # noqa: E501
            'index_adapter_kit_name': (str,),  # noqa: E501
            'index_adapter_kit_urn': (str,),  # noqa: E501
            'adapter_behavior': (str,),  # noqa: E501
            'override_cycles': (str,),  # noqa: E501
            'library': (LibraryCompact,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'sample_name': 'sampleName',  # noqa: E501
        'sample_urn': 'sampleUrn',  # noqa: E501
        'data_aggregation_group': 'dataAggregationGroup',  # noqa: E501
        'project_name': 'projectName',  # noqa: E501
        'library_name': 'libraryName',  # noqa: E501
        'library_urn': 'libraryUrn',  # noqa: E501
        'adapter_sequence_read1': 'adapterSequenceRead1',  # noqa: E501
        'adapter_sequence_read2': 'adapterSequenceRead2',  # noqa: E501
        'index_container_position': 'indexContainerPosition',  # noqa: E501
        'index1_sequence': 'index1Sequence',  # noqa: E501
        'index2_sequence': 'index2Sequence',  # noqa: E501
        'index1_name': 'index1Name',  # noqa: E501
        'index2_name': 'index2Name',  # noqa: E501
        'library_prep_kit_name': 'libraryPrepKitName',  # noqa: E501
        'library_prep_kit_urn': 'libraryPrepKitUrn',  # noqa: E501
        'index_adapter_kit_name': 'indexAdapterKitName',  # noqa: E501
        'index_adapter_kit_urn': 'indexAdapterKitUrn',  # noqa: E501
        'adapter_behavior': 'adapterBehavior',  # noqa: E501
        'override_cycles': 'overrideCycles',  # noqa: E501
        'library': 'library',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """LaneLibraryResponse - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            sample_name (str): Sample name. [optional]  # noqa: E501
            sample_urn (str): Sample URN. [optional]  # noqa: E501
            data_aggregation_group (str): Data aggregation group of the sample. [optional]  # noqa: E501
            project_name (str): Project Name of the sample  Note: This field is an alias of DataAggregationGroup field until DataAggregationGroups is deprecated.. [optional]  # noqa: E501
            library_name (str): Library name. [optional]  # noqa: E501
            library_urn (str): Library URN. [optional]  # noqa: E501
            adapter_sequence_read1 (str): Read 1 adapter sequence. [optional]  # noqa: E501
            adapter_sequence_read2 (str): Read 2 adapter sequence. [optional]  # noqa: E501
            index_container_position (str): The container position (well or plate+well position) for the library that is using index adapter kit with fixed index position. [optional]  # noqa: E501
            index1_sequence (str): Index 1 sequence  of the library. [optional]  # noqa: E501
            index2_sequence (str): Index 2 sequence of the library. [optional]  # noqa: E501
            index1_name (str): Name of index 1 sequence. [optional]  # noqa: E501
            index2_name (str): Name of index 2 sequence. [optional]  # noqa: E501
            library_prep_kit_name (str): Name of library prep kit. [optional]  # noqa: E501
            library_prep_kit_urn (str): URN of library prep kit. [optional]  # noqa: E501
            index_adapter_kit_name (str): Name of index adapter kit. [optional]  # noqa: E501
            index_adapter_kit_urn (str): URN of index adapter kit. [optional]  # noqa: E501
            adapter_behavior (str): Adapter behavior for this entry. [optional]  # noqa: E501
            override_cycles (str): Override cycles for this entry. [optional]  # noqa: E501
            library (LibraryCompact): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
