"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from ICA_SDK.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from ICA_SDK.model.workflow_run_compact import WorkflowRunCompact
    globals()['WorkflowRunCompact'] = WorkflowRunCompact


class WorkflowSignalCompact(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('description',): {
            'max_length': 256,
            'min_length': 0,
        },
        ('tenant_id',): {
            'max_length': 255,
            'min_length': 0,
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (str,),  # noqa: E501
            'urn': (str,),  # noqa: E501
            'href': (str,),  # noqa: E501
            'send_heartbeat_href': (str,),  # noqa: E501
            'send_success_response_href': (str,),  # noqa: E501
            'send_failure_response_href': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'status': (str,),  # noqa: E501
            'type': (str,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'inputs': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'workflow_run': (WorkflowRunCompact,),  # noqa: E501
            'timeout_seconds': (int,),  # noqa: E501
            'result': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'error': (str,),  # noqa: E501
            'error_cause': (str,),  # noqa: E501
            'created_by_client_id': (str,),  # noqa: E501
            'time_created': (datetime,),  # noqa: E501
            'time_modified': (datetime,),  # noqa: E501
            'created_by': (str,),  # noqa: E501
            'modified_by': (str,),  # noqa: E501
            'tenant_id': (str,),  # noqa: E501
            'acl': ([str],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'urn': 'urn',  # noqa: E501
        'href': 'href',  # noqa: E501
        'send_heartbeat_href': 'sendHeartbeatHref',  # noqa: E501
        'send_success_response_href': 'sendSuccessResponseHref',  # noqa: E501
        'send_failure_response_href': 'sendFailureResponseHref',  # noqa: E501
        'name': 'name',  # noqa: E501
        'status': 'status',  # noqa: E501
        'type': 'type',  # noqa: E501
        'description': 'description',  # noqa: E501
        'inputs': 'inputs',  # noqa: E501
        'workflow_run': 'workflowRun',  # noqa: E501
        'timeout_seconds': 'timeoutSeconds',  # noqa: E501
        'result': 'result',  # noqa: E501
        'error': 'error',  # noqa: E501
        'error_cause': 'errorCause',  # noqa: E501
        'created_by_client_id': 'createdByClientId',  # noqa: E501
        'time_created': 'timeCreated',  # noqa: E501
        'time_modified': 'timeModified',  # noqa: E501
        'created_by': 'createdBy',  # noqa: E501
        'modified_by': 'modifiedBy',  # noqa: E501
        'tenant_id': 'tenantId',  # noqa: E501
        'acl': 'acl',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """WorkflowSignalCompact - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): Unique resource ID. [optional]  # noqa: E501
            urn (str): URN of the resource. [optional]  # noqa: E501
            href (str): HREF to the resource. [optional]  # noqa: E501
            send_heartbeat_href (str): HREF to send a heartbeat to a workflow signal. [optional]  # noqa: E501
            send_success_response_href (str): HREF to succeed a workflow signal. [optional]  # noqa: E501
            send_failure_response_href (str): HREF to fail a workflow signal. [optional]  # noqa: E501
            name (str): Unique name of the signal. [optional]  # noqa: E501
            status (str): Current status of the signal. [optional]  # noqa: E501
            type (str): User-defined type associated with the signal. [optional]  # noqa: E501
            description (str): Description of the signal. [optional]  # noqa: E501
            inputs ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Inputs defined by the originating WaitForSignal state, in JSON.. [optional]  # noqa: E501
            workflow_run (WorkflowRunCompact): [optional]  # noqa: E501
            timeout_seconds (int): Signal timeout in seconds. The Signal will timeout if a heartbeat, succeed or fail is not received in this time interval.. [optional]  # noqa: E501
            result ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): The result of a successful signalling action in JSON.. [optional]  # noqa: E501
            error (str): The error of a failed signal.. [optional]  # noqa: E501
            error_cause (str): The error cause of a failed signal.. [optional]  # noqa: E501
            created_by_client_id (str): Client ID of the Origin Request. [optional]  # noqa: E501
            time_created (datetime): Time (in UTC) the resource was created. [optional]  # noqa: E501
            time_modified (datetime): Time (in UTC) the resource was modified. [optional]  # noqa: E501
            created_by (str): User that created the resource. [optional]  # noqa: E501
            modified_by (str): User that modified the resource. [optional]  # noqa: E501
            tenant_id (str): Tenant ID the resource belongs to. [optional]  # noqa: E501
            acl ([str]): Access control list of the resource. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
