"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from ICA_SDK.api_client import ApiClient, Endpoint as _Endpoint
from ICA_SDK.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from ICA_SDK.model.create_workflow_version_request import CreateWorkflowVersionRequest
from ICA_SDK.model.error_response import ErrorResponse
from ICA_SDK.model.launch_workflow_version_request import LaunchWorkflowVersionRequest
from ICA_SDK.model.update_workflow_version_request import UpdateWorkflowVersionRequest
from ICA_SDK.model.workflow_run import WorkflowRun
from ICA_SDK.model.workflow_version import WorkflowVersion
from ICA_SDK.model.workflow_version_list import WorkflowVersionList


class WorkflowVersionsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __create_workflow_version(
            self,
            workflow_id,
            **kwargs
        ):
            """Create a new workflow version  # noqa: E501

            Creates a new workflow version with a given workflow ID.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.create_workflow_version(workflow_id, async_req=True)
            >>> result = thread.get()

            Args:
                workflow_id (str): ID of the workflow

            Keyword Args:
                body (CreateWorkflowVersionRequest): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                WorkflowVersion
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['workflow_id'] = \
                workflow_id
            return self.call_with_http_info(**kwargs)

        self.create_workflow_version = _Endpoint(
            settings={
                'response_type': (WorkflowVersion,),
                'auth': [
                    'Bearer'
                ],
                'endpoint_path': '/v1/workflows/{workflowId}/versions',
                'operation_id': 'create_workflow_version',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'workflow_id',
                    'body',
                ],
                'required': [
                    'workflow_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'workflow_id':
                        (str,),
                    'body':
                        (CreateWorkflowVersionRequest,),
                },
                'attribute_map': {
                    'workflow_id': 'workflowId',
                },
                'location_map': {
                    'workflow_id': 'path',
                    'body': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__create_workflow_version
        )

        def __get_workflow_version(
            self,
            workflow_id,
            version_name,
            **kwargs
        ):
            """Get the details of a workflow version  # noqa: E501

            Gets the details for a workflow version with a given workflow ID and version name.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_workflow_version(workflow_id, version_name, async_req=True)
            >>> result = thread.get()

            Args:
                workflow_id (str): ID of the workflow
                version_name (str): Name of the workflow version

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                WorkflowVersion
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['workflow_id'] = \
                workflow_id
            kwargs['version_name'] = \
                version_name
            return self.call_with_http_info(**kwargs)

        self.get_workflow_version = _Endpoint(
            settings={
                'response_type': (WorkflowVersion,),
                'auth': [
                    'Bearer'
                ],
                'endpoint_path': '/v1/workflows/{workflowId}/versions/{versionName}',
                'operation_id': 'get_workflow_version',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'workflow_id',
                    'version_name',
                ],
                'required': [
                    'workflow_id',
                    'version_name',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'workflow_id':
                        (str,),
                    'version_name':
                        (str,),
                },
                'attribute_map': {
                    'workflow_id': 'workflowId',
                    'version_name': 'versionName',
                },
                'location_map': {
                    'workflow_id': 'path',
                    'version_name': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_workflow_version
        )

        def __launch_workflow_version(
            self,
            workflow_id,
            version_name,
            **kwargs
        ):
            """Launch a workflow version  # noqa: E501

            Launches a workflow version with a given workflow ID and version name.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.launch_workflow_version(workflow_id, version_name, async_req=True)
            >>> result = thread.get()

            Args:
                workflow_id (str): ID of the workflow
                version_name (str): Name of the workflow version

            Keyword Args:
                include ([str]): Comma-separated list of properties to include in the response. [optional]
                body (LaunchWorkflowVersionRequest): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                WorkflowRun
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['workflow_id'] = \
                workflow_id
            kwargs['version_name'] = \
                version_name
            return self.call_with_http_info(**kwargs)

        self.launch_workflow_version = _Endpoint(
            settings={
                'response_type': (WorkflowRun,),
                'auth': [
                    'Bearer'
                ],
                'endpoint_path': '/v1/workflows/{workflowId}/versions/{versionName}:launch',
                'operation_id': 'launch_workflow_version',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'workflow_id',
                    'version_name',
                    'include',
                    'body',
                ],
                'required': [
                    'workflow_id',
                    'version_name',
                ],
                'nullable': [
                ],
                'enum': [
                    'include',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('include',): {

                        "DEFINITION": "definition",
                        "ENGINEPARAMETERS": "engineParameters"
                    },
                },
                'openapi_types': {
                    'workflow_id':
                        (str,),
                    'version_name':
                        (str,),
                    'include':
                        ([str],),
                    'body':
                        (LaunchWorkflowVersionRequest,),
                },
                'attribute_map': {
                    'workflow_id': 'workflowId',
                    'version_name': 'versionName',
                    'include': 'include',
                },
                'location_map': {
                    'workflow_id': 'path',
                    'version_name': 'path',
                    'include': 'query',
                    'body': 'body',
                },
                'collection_format_map': {
                    'include': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__launch_workflow_version
        )

        def __list_all_workflow_versions(
            self,
            **kwargs
        ):
            """Get a list of all workflow versions  # noqa: E501

            Gets a list of workflow versions across all workflows.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.list_all_workflow_versions(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                tenant_id (str): ID of the tenant. [optional]
                include ([str]): Comma-separated list of properties to include in the response. [optional]
                page_size (int): Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified.. [optional] if omitted the server will use the default value of 10
                page_token (str): Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified.. [optional]
                sort (str): Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending).. [optional] if omitted the server will use the default value of "timeCreated asc"
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                WorkflowVersionList
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.list_all_workflow_versions = _Endpoint(
            settings={
                'response_type': (WorkflowVersionList,),
                'auth': [
                    'Bearer'
                ],
                'endpoint_path': '/v1/workflows/versions',
                'operation_id': 'list_all_workflow_versions',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'tenant_id',
                    'include',
                    'page_size',
                    'page_token',
                    'sort',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                    'include',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('include',): {

                        "TOTALITEMCOUNT": "totalItemCount"
                    },
                },
                'openapi_types': {
                    'tenant_id':
                        (str,),
                    'include':
                        ([str],),
                    'page_size':
                        (int,),
                    'page_token':
                        (str,),
                    'sort':
                        (str,),
                },
                'attribute_map': {
                    'tenant_id': 'tenantId',
                    'include': 'include',
                    'page_size': 'pageSize',
                    'page_token': 'pageToken',
                    'sort': 'sort',
                },
                'location_map': {
                    'tenant_id': 'query',
                    'include': 'query',
                    'page_size': 'query',
                    'page_token': 'query',
                    'sort': 'query',
                },
                'collection_format_map': {
                    'include': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__list_all_workflow_versions
        )

        def __list_workflow_versions(
            self,
            workflow_id,
            **kwargs
        ):
            """Get a list of workflow versions  # noqa: E501

            Gets a list of workflow versions with a given workflow ID.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.list_workflow_versions(workflow_id, async_req=True)
            >>> result = thread.get()

            Args:
                workflow_id (str): ID of the workflow

            Keyword Args:
                include ([str]): Comma-separated list of properties to include in the response. [optional]
                page_size (int): Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified.. [optional] if omitted the server will use the default value of 10
                page_token (str): Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified.. [optional]
                sort (str): Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending).. [optional] if omitted the server will use the default value of "timeCreated asc"
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                WorkflowVersionList
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['workflow_id'] = \
                workflow_id
            return self.call_with_http_info(**kwargs)

        self.list_workflow_versions = _Endpoint(
            settings={
                'response_type': (WorkflowVersionList,),
                'auth': [
                    'Bearer'
                ],
                'endpoint_path': '/v1/workflows/{workflowId}/versions',
                'operation_id': 'list_workflow_versions',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'workflow_id',
                    'include',
                    'page_size',
                    'page_token',
                    'sort',
                ],
                'required': [
                    'workflow_id',
                ],
                'nullable': [
                ],
                'enum': [
                    'include',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('include',): {

                        "TOTALITEMCOUNT": "totalItemCount"
                    },
                },
                'openapi_types': {
                    'workflow_id':
                        (str,),
                    'include':
                        ([str],),
                    'page_size':
                        (int,),
                    'page_token':
                        (str,),
                    'sort':
                        (str,),
                },
                'attribute_map': {
                    'workflow_id': 'workflowId',
                    'include': 'include',
                    'page_size': 'pageSize',
                    'page_token': 'pageToken',
                    'sort': 'sort',
                },
                'location_map': {
                    'workflow_id': 'path',
                    'include': 'query',
                    'page_size': 'query',
                    'page_token': 'query',
                    'sort': 'query',
                },
                'collection_format_map': {
                    'include': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__list_workflow_versions
        )

        def __update_workflow_version(
            self,
            workflow_id,
            version_name,
            **kwargs
        ):
            """Update an existing workflow version  # noqa: E501

            Updates an existing workflow version. Note: The Version, Definition, and Status cannot be changed simultaneously. Only one of these can be changed per API call.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.update_workflow_version(workflow_id, version_name, async_req=True)
            >>> result = thread.get()

            Args:
                workflow_id (str): ID of the workflow
                version_name (str): Name of the workflow version

            Keyword Args:
                body (UpdateWorkflowVersionRequest): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                WorkflowVersion
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['workflow_id'] = \
                workflow_id
            kwargs['version_name'] = \
                version_name
            return self.call_with_http_info(**kwargs)

        self.update_workflow_version = _Endpoint(
            settings={
                'response_type': (WorkflowVersion,),
                'auth': [
                    'Bearer'
                ],
                'endpoint_path': '/v1/workflows/{workflowId}/versions/{versionName}',
                'operation_id': 'update_workflow_version',
                'http_method': 'PATCH',
                'servers': None,
            },
            params_map={
                'all': [
                    'workflow_id',
                    'version_name',
                    'body',
                ],
                'required': [
                    'workflow_id',
                    'version_name',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'workflow_id':
                        (str,),
                    'version_name':
                        (str,),
                    'body':
                        (UpdateWorkflowVersionRequest,),
                },
                'attribute_map': {
                    'workflow_id': 'workflowId',
                    'version_name': 'versionName',
                },
                'location_map': {
                    'workflow_id': 'path',
                    'version_name': 'path',
                    'body': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json-patch+json',
                    'application/json',
                    'text/json',
                    'application/*+json'
                ]
            },
            api_client=api_client,
            callable=__update_workflow_version
        )
